Development
HansenBerlin/altenheim-kalender pull request #164
Opened 2021-06-11 13:34 UTC by HansenBerlin

Achtung Mega-PR (sorry :-) ) Habe einige Male ohne PR in den DEV gemergt weil viel so grundsätzliches Architekturzeug war. Dementsprechend fällt das jetzt hier etwas umfangreicher aus. Ich werde hier in den PR Kommentare bei den changed Files reinschreiben damit ihr das ein oder andere vielleicht besser nachvollziehen könnt.

Ist jetzt vielleicht von der Struktur her so auf den ersten Blick nicht so einfach zu blicken, aber guckt bitte auf jeden Fall gut durch, stellt Fragen wenn was unklar ist und kommentiert wenn Dinge unlogisch erscheinen, der Codestyle nicht stimmt usw. 

Wenn das dann soweit durch ist haben wir nen ganz guten Stand auf dem wir in/nach diesem Sprint die ganzen Funktionen an denen ihr grad entwickeln einstöpseln. Das wird ein Fest. :-)

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/AppointmentEntryFactory.java
> +
Übergabe der Sammlung aller Kalender, weil die Factory hier reinschreibt. Zur Zeit noch mit dem Zufallsgenerator, das wird natürlich später ersetzt, so dass, wenn Einträge gemacht werden hier gesteuert wird in welchen Kalender sie geschrieben werden und anschließend gespeichert wird. Die View wird übergeben um bei Update zu rendern, das ist nicht so richtig sauber und gehört hier eigentlich nicht hin sondern in den entsprechenden ViewController. Bzw. eigentlich müsste hier ein Listener regisitriert sein,  so dass beim Update der Collections ein Renderupdate erfolgt - glaube dafür hat CalenderFX gute Möglichkeiten. Aber erstmal ist es für das Sprintziel und den Einbau der Funktionen  ne pragmatische Lösung.

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/AppointmentEntryFactory.java
> +		var result = allCalendars.getAllCalendars();
Die Methode wirkt etwas redundant, weil die Entrys im Kalender auch als Hashmaps gespeichert sind. Hintergrund ist der Export, für den wir die einzelnen Entrys von je einem Kalender brauchen, intern werden diese Einträge aber je Tag als Liste gespeichert.  Der Key der Hashmap ist hier der Name des Kalenders, die auch für die Serialsierung benötigt wird um individuelle Dateien je Kalender zu erzeugen die wir beim Laden auch wieder zuordnen können. Aber da kann die Import-Export Firma bei euch auch nochmal gucken ob das nicht besser/kürzer/schöner geht, hab das hier ziemlich unbedacht ins Keyboard gehackt.

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/AppointmentEntryFactory.java
> +        calendar.setName(String.format("%d", calendar.hashCode()));
Als Name wird hier erstmal der Hashcode verwendet weil der mit ziemlich hoher Wahrscheinlichkeit unique ist. Muss aber für den Produktivcode natürlich noch anders erfolgen (aus den Settings oder mit Defaultwerten).

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/AppointmentEntryFactory.java
> +                for (int k = 8; k < 20 ; k+=2)
Alles nur zur Erzeugung der zufälligen Kalendereinträge zum Testen, sowas wie der equals oben geht natürlich eigentlich nicht...aber da das nicht im Produktivcode landet ists egal, nur nicht abgucken. :-)

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/AppointmentEntryFactory.java
> +
s.o., reine Hilfsmethoden die später rausfliegen)

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/ChangeListener.java
> +
Testweise Implementierung der PropertyChangeListener aus Beans, damit wir nicht alle Werte die sich oft ändern händisch ändern müssen. Klappt super da müssen wir uns mal commiten wo wir das anwenden wollen.

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/ExportController.java
> +
Müssen mal sehen ob das so hinhaut bei den Objektabhängigkeiten, erstmal leere Klasse in die Import Export ihre Methoden dann implementieren kann.

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/GoogleAPIController.java
> +    private static final String FINDDESTINATIONSQUERY= "https://maps.googleapis.com/maps/api/distancematrix/json?origins=%s&destinations=%s&key=%s";
Die Wildcard %s muss hier mit dem API Key ersetzt werden, der aber nicht öffentlich sein darf. Im Prototyp hatte ich das mit drin weil das repo auf private war, jetzt ist es public und ich hab den Key hier (und auch bei Google natürlich gelöscht). Im Produktivcode muss der Key in den Settings liegen in einer File die von Git nicht getrackt wird und natürlich auch nicht reverse engineered werden kann, also als Hashvalue (Java hat da eigene Klassen für sowas).

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/IOController.java
> +
In dieser Klasse (von denen einige andere erben) werden alle Operationen fürs Schreiben und Lesen vom und auf die Festplatte verwaltet. Die Schreib und Lesemethoden für den Kalender habe ich mal aus eurem Import/Export Branch übernommen, da sie IO Zugriffe machen müssen wir überlegen ob Import-Export die Klasse erbt oder wir das nochmal splitten.

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/IOController.java
> +        var allCalendars = administrateEntries.createEntryListForEachCalendar();
Der Kalender wird nicht serialisiert, was performancetechnisch zwar ginge (habs mit 100k Einträgen getestet) aber durch die komplexe Objektstruktur zu Problemen und Fehlern führt. Deshalb wird der Kalender anders als zB die Kontakte (s.u) als ICS File gesichert und geladen - was zudem deutlich performanter ist als Serialization.

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/IOController.java
> +
beides sind Helfermethoden fürs Lesen und Schreien der Kalender.

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/ImportController.java
> +    private IWebsiteScraperController scraper;
analog zu Exportcontroller - erstmal leere Klasse mit einem Vorschlag für die benötigten Objekte (Services)

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/SettingsController.java
> +
Dieser noch leere Controller verwaltet später die Settings (das wäre so ein Fall für Databinding mit dem Settingsmodel).

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/SmartSearchController.java
> +		var result = administrateEntries.getSpecificCalendarByIndex(0).findEntries(
Herz der Angelegenheit. Schönes Pairprogramming mit Nico S., diese Methode ermittelt freie Slots in Abhängigkeit des Nutzerwunsches (Parameter Entry) und speichert diese wiederum als Liste von neuen Entries. Dem wird noch eine Methode vorgelagert sein, die die Nutzereingaben aufbereitet (Anfahrt usw.) und eine nachgestellte Methode die dann in diesen Slots automatisch oder nach Userwunsch die Termine festlegt.

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/SmartSearchController.java
> +		long end = input.getEndMillis();
Die Frage kam auf warum die Millis. Ist einfach die fehlertoleranteste und zudem auch ziemlich schnelle Art für Zeitvergleiche (wen's interessiert: das ist die Unix Epoch Time seit dem 1.1.1970).

2021-06-11 14:35 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/SmartSearchController.java
> +					output.remove(output.size()-1);
Denke bis hierhin ist die Funktionsweise einigermaßen klar, der Check nach Duplicates hat mit der internen Datenverwaltung der Calendarobjekte zu tun. Hier wird einfach nur sichergestellt, dass bei mehrtägigen Termine die dadurch erzeugten mehrfachen Entrys sofort entfernt werden. So baut sich im Stack gar nicht erst unnötiger Datenmüll auf.

2021-06-11 14:37 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/logicController/WebsiteScraperController.java
> +        var timer = new Timer();
Klasse soweit leer, weil sie vom HWR Scraper Team ja grad implementiert wird, hier nur ein Test für einen Task der als Background Worker (also ohne den Mainthread zu blocken) im festgelegten Intervallen das ausführt, was später unten in der run() Methode steht (ist ein Overwrite, Name muss also so bleiben)

2021-06-11 14:40 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/viewController/SearchViewController.java
> +        var testEntry = entryFactory.createUserSettingsEntry(timeStart.getValue(), timeEnd.getValue());
Diese Funktionen  gehören hier nicht rein, habe sie aber einfach zum Ausprobieren mangels passender View durch den Buttonklick ausprobiert. Also Daten soeichern (und hier noch zufällig erzeugen erstmal) und laden und ein dynamisches Update der Liste mit den Vorschlägen. Zum Ausprobieren jeweils ein/auskommentieren, Aufruf in der Smart Search View über den Button "SPEICHERN".

2021-06-11 14:43 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/controller/viewController/SearchViewController.java
> +        startColumn.setCellValueFactory(new PropertyValueFactory<SuggestionsModel, String>("startTime"));
Die Tables müssen wir leider wie es scheint dynamisch bauen, da hier OberservableCollections durchaus Sinn machen und diese mit durch FX initialisierte Objekte nicht so richtig zu funktionieren scheinen. Aber da Tables UI technisch gesehen trivial sind soltle das kein Prob sein. Aber wenn da jemand ne Idee hat oder das mal anders testen will könnte das als Verständnisgrundlage dienen (die Property Value Factory registriert die Veränderungen in der definierten Klasse (SuggestionsModel)).

2021-06-11 14:51 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/models/ContactModel.java
> +import java.util.Map;
Model für das Speichern der Kontakte, guckt mal ob was fehlt.

2021-06-11 14:52 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/models/SettingsModel.java
> +    private String pathToSaveBackupFiles = null;
Hier können wir später die Events registrieren wenn Settings geändert werden (so dass diese programmweit aktiv werden und ggfs auch direkt gespeichert werden)

2021-06-11 14:57 UTC, HansenBerlin commented on src/test/java/com/altenheim/kalender/SmartSearchControllerTest.java
> +
Unittests für die mittlere Methode des SmartSearchControllers. Würde ich jetzt hier nicht weiter drauf eingehen, aber die Methodennamen sagen was über die Testcases aus. Bitte kommentieren wenn euch da noch welche einfallen. Bzgl. Codestyle sind hier einige Regeln aufgehoben (zB. was Redundanzen angeht), also zerbrecht euch nicht den Kopf was mich hier geritten hat...

2021-06-11 14:58 UTC, HansenBerlin reviewed
Habe das hier mal etwas umfangreicher kommentiert um es nachvollziehbar zu machen.

2021-06-11 15:46 UTC, Stier-09 requested changes

2021-06-11 15:46 UTC, Stier-09 commented on src/main/java/com/altenheim/kalender/interfaces/IIOController.java
> +    public void loadContactsTFromFile() throws IOException, ClassNotFoundException;
loadContactsFromFile()

2021-06-11 15:46 UTC, Stier-09 commented on src/main/java/com/altenheim/kalender/models/ContactModel.java
> +import java.util.Map;
Adresse

2021-06-11 15:51 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/models/ContactModel.java
> +import java.util.Map;
Wird überbewertet. Wir machen die Wegfindung mit dem UML Tool von IntelliJ. ;-)

2021-06-12 16:24 UTC, nicoregenberg commented on src/main/java/com/altenheim/kalender/interfaces/IIOController.java
> +    public void writeMailTeamplates(MailTemplateModel templates);
writeMailTemplates()

2021-06-12 16:26 UTC, nicoregenberg commented on src/main/java/com/altenheim/kalender/models/ContactModel.java
> +import java.util.Map;
Aber abspeichern der Adresse macht doch Sinn für jeden Kontakt? 🤔

2021-06-12 16:30 UTC, nicoregenberg approved these changes
super Hannes!!!
Danke für die Kommentare als Übersicht, die haben definitiv sehr geholfen.

2021-06-12 22:17 UTC, HansenBerlin commented on src/main/java/com/altenheim/kalender/models/ContactModel.java
> +import java.util.Map;
Spaß. Natürlich brauchen wir die Adresse. ;-) Ist zwar eigentlich nicht Scope von diesem PR gewesen aber ich mache es noch schnell rein. Zudem auch die Öffnungszeiten noch.

2021-06-12 22:27 UTC, merged